# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: convert2rhel.spec

# add or remove files that should be synced
files_to_sync:
    - convert2rhel.spec
    - .packit.yaml

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: convert2rhel
upstream_project_url: https://github.com/oamg/c2r-mock-utility
# downstream (Fedora) RPM package name
downstream_package_name: convert2rhel


jobs:
  # Build for pull request push
  - job: copr_build
    owner: "@oamg"
    project: c2r-mock-utility
    trigger: pull_request
    targets:
      - epel-7-x86_64
    actions:
      # Get the version from the spec file
      get-current-version:
      - grep -oP '^Version:\s+\K\S+' convert2rhel.spec
  # Build for merge to devel
  - job: copr_build
    owner: "@oamg"
    project: c2r-mock-utility
    trigger: commit
    branch: main
    targets:
      - epel-7-x86_64
    actions:
      # Get the version from the spec file
      get-current-version:
      - grep -oP '^Version:\s+\K\S+' convert2rhel.spec
